Presentation/Market.Site/Models/LogInModel.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Market.Site.Models
{
    public class LogInModel
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [HiddenInput]
        public string ReturnUrl { get; set; }
    }
}

Presentation/Market.Site/Controllers/AuthController.cs
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using Market.Site.Models;
using Microsoft.Owin;
using Microsoft.Owin.Security;

namespace Market.Site.Controllers
{
    [AllowAnonymous]
    public class AuthController : BaseController
    {
        [HttpGet]
        public ActionResult LogIn(string returnUrl)
        {
            var model = new LogInModel
            {
                ReturnUrl = returnUrl
            };
            return View(model);
        }
        [HttpPost]
        public ActionResult LogIn(LogInModel model)
        {
            if (!ModelState.IsValid)
                return View();

            if (model.Email == "admin@market.com" && model.Password == "password")
            {
                var claims = new[]
                {
                    new Claim(ClaimTypes.Name, "admin@market.com"),
                    new Claim(ClaimTypes.Email, "admin@market.com"),
                    new Claim(ClaimTypes.Country, "Argentina"),
                };
                var identity = new ClaimsIdentity(claims, "ApplicationCookie");
                IOwinContext ctx = Request.GetOwinContext();
                IAuthenticationManager authManager = ctx.Authentication;
                authManager.SignIn(identity);
                return Redirect(GetRedirectUrl(model.ReturnUrl));
            }
            ModelState.AddModelError("", "El correo electrónico o la contraseña no son válidos.");
            return View();
        }
        public ActionResult LogOut()
        {
            var ctx = Request.GetOwinContext();
            var authManager = ctx.Authentication;

            authManager.SignOut("ApplicationCookie");
            return RedirectToAction("Index", "Home");
        }


    }
}

Presentation/Market.Site/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Market.Site.Controllers
{
    public abstract class BaseController : Controller
    {
        //public UserViewModel CurrentUser => new UserViewModel(this.User as ClaimsPrincipal);

        protected string GetRedirectUrl(string returnUrl)
        {
            if (string.IsNullOrEmpty(returnUrl) || !Url.IsLocalUrl(returnUrl))
            {
                return Url.Action("Index", "Home");
            }

            return returnUrl;
        }
    }
}

Presentation/Market.Site/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Market.Business;
using Market.Entities.Models;

namespace Market.Site.Controllers
{
    public class CategoryController : Controller
    {
        public ActionResult Index()
        {
            var biz = new CategoryBiz();
            var model = biz.Listar();
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Category model)
        {
            if(!ModelState.IsValid)
                return View();

            try
            {
                var biz = new CategoryBiz();
                biz.Agregar(model);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                /// Que pasa con el error -> Bitacoras
                Console.WriteLine(e);
                return View(model);
            }
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var biz = new CategoryBiz();
            var model = biz.Get(id);
            return View(model);
        }
        [HttpPost]
        public ActionResult Delete(Category model)
        {
            var biz = new CategoryBiz();
            biz.Eliminar(model);
            return RedirectToAction("Index");
        }

    }
}

Presentation/Market.Site/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace Market.Site.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            //var claimsIdentity = User.Identity as ClaimsIdentity;
            //ViewBag.Country = claimsIdentity.FindFirst(ClaimTypes.Country).Value;

            return View();
        }
    }
}

Presentation/Market.Site/Views/Category/Create.cshtml
@model Market.Entities.Models.Category
@{
    ViewBag.Title = "Create Category";
}

@using (Html.BeginForm())
{
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Presentation/Market.Site/Views/Category/Delete.cshtml
@model Market.Entities.Models.Category

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Presentation/Market.Site/Views/Category/Index.cshtml
@model IEnumerable<Market.Entities.Models.Category>
@{
    ViewBag.Title = "Index Category";
}
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>

Presentation/Market.Site/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index Home";
}


<h2>@ViewBag.Title</h2>

<p>
    Hola @User.Identity.Name
</p>
<p>
    Usuario residente de: @ViewBag.Country
</p>

<div>
    <h4 id="output"></h4>
</div>
<script id="script" src="/scripts/demo.js"></script>
<script src="/scripts/appJS/app.js"></script>

<div class="row">
    <button class="btn btn-default" onclick="displayText()">Display Text</button>
    <div id="msgDiv">
        <h2 id="msgText"></h2>
    </div>

</div>

Presentation/Market.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/site.css" rel="stylesheet" />
    <script src="~/Scripts/utils.js"></script>
</head>
<body>
    <div id="contenedor">
        <div id="cabecera">
            <div id="logo">
                <h1></h1>
            </div>
            <div id="buscador">
                <form action="#" method="post">
                    Buscar &nbsp;
                    <input name="busqueda" type="text" />
                </form>
            </div>
            <div class="clear">
            </div>
        </div>
        <div id="menu">
            <ul id="menu_principal">
                <li> <a href="/">Home</a> </li>
                <li>
                    <a href="@Url.Action("Index", "Category")">Categorias</a>
                </li>
                <li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a href="@Url.Action("LogOut", "Auth")">Log Out</a>
                    }
                </li>
            </ul>
        </div>
        <div id="contenido">
            <div id="principal">
                @RenderBody()
            </div>
            @*<div id="secundario">
                <h2> Opciones secundarias</h2>
            </div>*@
        </div>
        <div id="pie">
            <p> Datos de la WebSite - 2021</p>
        </div>

    </div>
    
    
</body>
</html>